### ISSUE TITLE
v0.3.0 beta checklist

### ISSUE THREAD

**Issue by 255kb** [255kb/mockoon#20]
- [x] Bump app version

**Builds:** 
- [x] Build Windows version
- [x] Build Linux version
- [x] Build OSX version

**Tests:**
- [x] Test Windows version
- [x] Test Linux version
- [x] Test OSX version

**Publish:**
- [x] Publish Windows binaries
- [x] Publish Linux binaries
- [x] Publish OSX binaries
- [x] Publish update file
- [x] Create release on repository
- [x] Update website with new versions
- [x] Update website's feature list
- [x] Update Github issues
- [x] Spread the word!
  - [x] Plan posts on social networks
  - [x] Send newsletter
