### ISSUE TITLE
v0.4.0 beta checklist

### ISSUE THREAD

**Issue by 255kb** [255kb/mockoon#27]
- [x] Bump app version

**Builds:** 
- [x] Build  and sign Windows version
- [x] Build Linux version
- [x] Build OSX version

**Tests:**
- [x] Test Windows version
- [x] Test Linux version
- [x] Test OSX version

**Publish:**
- [x] Publish Windows binaries
- [x] Publish Linux binaries
- [x] Publish OSX binaries
- [x] Publish update file
- [x] Create release on repository
- [x] update repo wording (open source)
- [x] Update website with new versions
- [x] Update website's feature list
- [x] Update website's wording for open source
- [x] publish website
- [x] move code on main repo
- [x] Update Github issues
- [x] Spread the word!
  - [x] Plan posts on social networks
  - [x] Send newsletter
