### ISSUE TITLE
v1.1.0 checklist

### ISSUE THREAD

**Issue by 255kb** [255kb/mockoon#58]
- [x] Bump app version

**Tests:**
- [x] Test Windows build
- [x] Test Linux build
- [x] Test OSX build

**Builds:** 
- [x] Build and sign Windows version
- [x] Build Linux version
- [x] Build OSX version

**Publish:**
- [x] Create release on repository
- [x] Add Windows binaries to release
- [x] Add Linux binaries to release
- [x] Add  OSX binaries to release
- [x] Merge website branch
- [x] Publish website
- [x] Close / update Github issues
- [x] Spread the word!
  - [x] Plan posts on social networks
