### ISSUE TITLE
v1.2.0 checklist

### ISSUE THREAD

**Issue by 255kb** [255kb/mockoon#68]
- [x] Bump app version

**Builds:** 
- [x] Build and sign Windows version
- [x] Build Linux version
- [x] Build OSX version

**Tests:**
- [x] Test Windows build
- [x] Test Linux build
- [x] Test OSX build

**Publish:**
- [x] Create release on repository
- [x] Add Windows binaries to release
- [x] Add Linux binaries to release
- [x] Add OSX binaries to release
- [x] Publish release
- [x] Update website versions
- [x] Merge website branch
- [x] Publish website on Firebase
- [x] Update wiki
- [x] Merge wiki branch
- [x] Update homebrew cask
- [x] Close / update Github issues
- [x] Spread the word!
