### ISSUE TITLE
Next release checklist

### ISSUE THREAD

**Issue by 255kb** [255kb/mockoon#82]
- [x] Bump app version

**Builds:** 
- [x] Build and sign Windows version
- [x] Build Linux version
- [x] Build OSX version

**Tests:**
- [x] Test Windows build
- [x] Test Linux build
- [x] Test OSX build

**Release:**
- [x] Create release on repository
- [x] Add Windows binaries to release
- [x] Add Linux binaries to release
- [x] Add OSX binaries to release
- [x] Publish release

**Website:**
- [x] Update website versions
- [x] Merge website branch
- [x] Publish website on Firebase

**Wiki:**
- [x] Update wiki
- [x] Merge wiki branch

**Distribution:**
- [x] Update homebrew cask
- [x] Update choco

**Misc:**
- [x] Close / update Github issues
- [x] Spread the word!
